### ISSUE TITLE
Seems not to work with Version 128

### ISSUE THREAD

**Issue by juersimon** [That-Developer-Guy/Send-Later-Button-Thunderbird#1]
There is no Button in Version 128

**Comment by That-Developer-Guy** [comment]
I'm sorry to hear that. When I tried it in Thunderbird 128, it worked seamlessly. I also haven't been able to locate any issues that may have caused the button to disappear. My suggestion is to try reinstalling the addon by removing it and installing it again.
If the issue persists, you can write a reply to this comment and I'll look into it again.

**Comment by 03302024** [comment]
I am also facing this issue. I removed and reinstalled again with no luck. I am on Thunderbird 128.3.0esr (64-bit).
