### ISSUE TITLE
Grayed out button on Thunderbird 128.4.3

### ISSUE THREAD

**Issue by 03302024** [That-Developer-Guy/Send-Later-Button-Thunderbird#4]
Using Thunderbird 128.4.3 and Send Later Button 1.2.2, the button is grayed out.

**Comment by 03302024** [comment]
I figured out that if I "create a new message", the button is grayed out; but if I "reply to" a message, the button is enabled then.

**Comment by That-Developer-Guy** [comment]
Hi,
I am sorry for the late response. Regarding your problem I can't locate any issues in the code. However the button grays out if the recipient address is not specified or incorrect. This is checked through a simple pattern recognition. If you write a reply the recipient adress gets filled with the address of the person you are replying to and thus the button is activated. If you just create a new message, the recipient address is not specified and the button is grayed out. The reason I implemented this is that it will give you an error mesage when you try to send the mail with an unspecified or incorrect recipient address. That could be an explanation for the problem you are encountering. If this was indeed your problem, I am glad to have helped, if not you can comment here again and I'll look into it further.

**Comment by 03302024** [comment]
> Hi

Hi

> If you just create a new message, the recipient address is not specified and the button is grayed out.

Thank you for the explanation. I wasn't expecting this, as it is different to the behaviour of "File > Send Later" menu item.

> The reason I implemented this is that it will give you an error mesage when you try to send the mail with an unspecified or incorrect recipient address.

There are occations that you wouldn't want to specify the To field, but want to specify the Bcc field. In such scenario, the recipients recive the email with "undisclosed-recipient" in the To field. Well, the "File > Send Later" menu item is always there to be utilized, if needed..

> That could be an explanation for the problem you are encountering.

Yes, it is.

> I am glad to have helped

Thank you for your help.

**Comment by 03302024** [comment]
I would like to suggest please make this behaviour optional, by adding a checkbox in the add-on's  Options window.

**Comment by That-Developer-Guy** [comment]
I just released a new version which I believe solves your problem. You can now just specify the bcc entry (or the cc entry) and it will activate the button regardless, but gray it out if none of the entries was defined.

**Comment by 03302024** [comment]
> I just released a new version

Yes, this got much better. Thank you.

**Comment by 03302024** [comment]
Hi again, I just discovered another senario that the Send Later button is grayed out: When the netwok/internet is not available.

I wish I could bypass this button disabling feature altogether. by a checkbox in the add-on's Option page.

**Comment by That-Developer-Guy** [comment]
Hi,
I think I am not really understanding the issue. As far as I am aware, the button isn't needed when the internet connection is off, because Thunderbird defaults the send button to a send later button if the internet connection is off or disabled in Thunderbird. Because of this, the addon disables the button in offline mode, as it is not needed then. Is that your issue? Am I misunderstanding something here? Please let me know what I don't understand and I'll try to help.

**Comment by 03302024** [comment]
> Am I misunderstanding something here? 

You are considering one usage case again, and that is you have both "Send" and "Send later" buttons on the toolbar. Then you go the extra step to decide which button to click based on if the internet is available. A task that should have no extra flow chart rules to follow.

> Please let me know what I don't understand and I'll try to help.

I opt for simplicity. I always do "send later" rather than "send". So I have only "Send Later" button on the toolbar.

Moreover, the original Thunderbird "Send Later" menu item doesn't have these extra features. And there is some reasons for that, as I have described in this thread. 

Certainly, it is your app, your choice. I am just saying your add-on has unexpected surprises for users, that may make it difficult for them to use. Best would be to make those extra features optional.

**Comment by That-Developer-Guy** [comment]
Hi,
I now understand what you meant and I therefore uploaded a new version which adds the requested feature. If you have other suggestions or problems, don't hesitate to ask. Feedback is always welcome!

**Comment by 03302024** [comment]
Thank you for the new version. I have a comment for you:

Suppose I go to the Options page and click on "Enable button in offline mode" and then click on "Save Settings" button. Then I close the Options page. The setting works just fine. 

Now, if I go to the Options page again, I see the setting reverts back to "Disable button in offline mode". While it is expected that the previous setting, be persistent and visiting the Options page again show the previously selected "Enable button in offline mode".

**Comment by That-Developer-Guy** [comment]
Thanks again for the feedback, I did indeed miss a rather avoidable bug. With the new version this bug should now be resolved.

**Comment by 03302024** [comment]
Thanks for the new version. It works as expected.
